apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.names.networkpolicy }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.labels.app }}
  policyTypes:
    - Ingress
    - Egress
  
  # Ingress: Solo permitir tráfico desde backend-api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend-api
      ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
  
  # Egress: Permitir salida a PostgreSQL y DNS
  egress:
    # Permitir conexión a PostgreSQL
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
    
    # Permitir DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
      ports:
        - protocol: UDP
          port: 53
    
    # Permitir API server
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: openshift-kube-apiserver
      ports:
        - protocol: TCP
          port: 443
