{{- if and (hasKey .Values "route") (hasKey .Values.route "enabled") .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mi.fullname" . }}
  labels:
    {{- include "mi.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "mi.fullname" . | replace "mi-deployment" "mi-servicio" }}
  port:
    targetPort: http
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  {{- if and (hasKey .Values.route "tls") .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
{{- end }}
