# mi-chart/templates/pvc.yaml
{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    {{- include "mi.labels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.pvc.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}
{{- end }}